# create centos with vim,ifconfig

# Basic image
FROM centos
MAINTAINER JW<jwl515@gmail.com>

# set root
ENV MYPATH /usr/local
WORKDIR $MYPATH

# install vim
RUN yum -y install vim
# install ifconfig
RUN yum -y install net-tools

EXPOSE 80
CMD echo $MYPATH
CMD echo "success----------ok"
CMD /bin/bash
